apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: url-forkorter
  namespace: the-g-team
  annotations:
    texas.nais.io/enabled: "true"
spec:
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true
  ingresses:
    - https://url-forkorter.ekstern.dev.nav.no
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
  observability:
    logging:
      destinations:
        - id: loki
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-f1-micro
        databases:
          - name: postgres-url-forkorter
