name: Build and deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Build, push and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: the-g-team
          identity_provider: nais-management-ddba
          project_id: projects/636929582051/locations/global/workloadIdentityPools/test-nais-identity-pool/providers/github-oidc-provider
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: sandbox
          RESOURCE: .nais/app.yaml
          VAR: image=${{ steps.docker-build-push.outputs.image }}
          DEPLOY_SERVER: deploy.test-nais.cloud.nais.io:443
