name: Build and deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Build, push and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: "gar-bachelor-url-forkorte-51cb@${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}.iam.gserviceaccount.com"
          token_format: "access_token"
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: "europe-north1-docker.pkg.dev/${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}/bachelor-url-forkorter"
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
      - name: Build and push
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # ratchet:docker/build-push-action@v5
        id: build_push
        with:
          push: true
      - run: echo "${{ steps.build_push.outputs.metadata }}" | jq .
      - name: Deploy to Nais
        uses: nais/deploy/actions/deploy@6fdb8f73f1d1e4ec8bf24bd371929cdedb118dbf
        env:
          CLUSTER: sandbox # Replace
          RESOURCE: .nais/app.yaml # This points to the file we created in the previous step
          VAR: image=${{ fromJSON(steps.build_push.outputs.metadata).tags[0] }}
          DEPLOY_SERVER: deploy.test-nais.cloud.nais.io:443
